export const priceCopy = {
  hr: {
    title: 'Cjenici i informacije o cijenama', reference: 'Cijena na', current: 'Trenutačna cijena',
    explanation: 'Uz trenutačnu cijenu prikazujemo redovnu cijenu na navedeni datum, prema hrvatskim pravilima o transparentnosti cijena. Taj podatak služi usporedbi, nije oznaka popusta i prikazuje se i kada se cijena nije promijenila.',
    full: 'Cijeli cjenik · CSV', daily: 'Dnevna marenda · CSV', archive: 'Arhiva cjenika', published: 'Objavljeno',
    sources: 'Službeni izvori', guidance: 'Pojašnjenje Ministarstva gospodarstva',
    tiers: 'Marenda ima šest cjenovnih razreda. Uz svaki razred prikazujemo jelo koje danas pripremamo. Jela se mijenjaju, a ponuda vrijedi do isteka dnevne količine.',
    stale: 'Za današnju marendu, cijene i alergene obratite se osoblju u Bistro Putniku.',
    offerDate: 'Ponuda za', breakfast: 'Doručak buffet',
    downloadNote: 'CSV datoteke možete otvoriti u Excelu i drugim programima za proračunske tablice. Cijene su u eurima, s uključenim PDV-om.',
    dailyNote: 'Dnevni CSV opisuje ponudu samo za navedeni datum. Cijeli cjenik uključuje imenovana jela posljednje objavljene dnevne ponude.',
  },
  en: {
    title: 'Price lists & price information', reference: 'Price on', current: 'Current price',
    explanation: 'Beside the current price, we show the regular price on the stated date under Croatian price-transparency rules. It is a reference for comparison, not a discount, and is shown even when the price has stayed the same.',
    full: 'Full price list · CSV', daily: 'Daily lunch · CSV', archive: 'Price list archive', published: 'Published',
    sources: 'Official sources', guidance: 'Ministry of Economy guidance',
    tiers: 'Marenda has six price levels. Each level shows the dish we are preparing today. Dishes change daily and are available while the day’s quantity lasts.',
    stale: 'Please ask our team at Bistro Putnik for today’s lunch dishes, prices and allergen information.',
    offerDate: 'Offer for', breakfast: 'Breakfast buffet',
    downloadNote: 'CSV files open in Excel and other spreadsheet applications. Prices are in euros and include VAT.',
    dailyNote: 'The daily CSV describes the offer only for its stated date. The full list includes named dishes from the most recently published daily offer.',
  },
  de: {
    title: 'Preislisten & Preisinformationen', reference: 'Preis am', current: 'Aktueller Preis',
    explanation: 'Neben dem aktuellen Preis zeigen wir gemäß den kroatischen Vorschriften zur Preistransparenz den regulären Preis am angegebenen Datum. Er dient dem Vergleich, ist kein Rabatt und wird auch bei unverändertem Preis angezeigt.',
    full: 'Gesamte Preisliste · CSV', daily: 'Mittagstisch · CSV', archive: 'Preislistenarchiv', published: 'Veröffentlicht',
    sources: 'Offizielle Quellen', guidance: 'Erläuterungen des Wirtschaftsministeriums',
    tiers: 'Marenda hat sechs Preisstufen. Bei jeder Stufe steht das Gericht, das wir heute zubereiten. Die Gerichte wechseln täglich und sind erhältlich, solange der Tagesvorrat reicht.',
    stale: 'Fragen Sie unser Team im Bistro Putnik nach den heutigen Mittagsgerichten, Preisen und Allergenen.',
    offerDate: 'Angebot für', breakfast: 'Frühstücksbuffet',
    downloadNote: 'CSV-Dateien lassen sich in Excel und anderen Tabellenprogrammen öffnen. Die Preise sind in Euro inklusive Mehrwertsteuer.',
    dailyNote: 'Die Tages-CSV gilt nur für das angegebene Datum. Die gesamte Preisliste enthält die namentlich aufgeführten Gerichte des zuletzt veröffentlichten Tagesangebots.',
  },
  sv: {
    title: 'Prislistor & prisinformation', reference: 'Pris den', current: 'Aktuellt pris',
    explanation: 'Bredvid det aktuella priset visar vi det ordinarie priset på angivet datum enligt kroatiska regler om pristransparens. Det är en jämförelse, inte en rabatt, och visas även när priset är oförändrat.',
    full: 'Fullständig prislista · CSV', daily: 'Dagens lunch · CSV', archive: 'Prislistarkiv', published: 'Publicerad',
    sources: 'Officiella källor', guidance: 'Ekonomiministeriets vägledning',
    tiers: 'Marenda har sex prisnivåer. Vid varje nivå visas rätten vi lagar idag. Rätterna ändras dagligen och serveras så länge dagens portioner räcker.',
    stale: 'Fråga vår personal på Bistro Putnik om dagens lunchrätter, priser och allergener.',
    offerDate: 'Erbjudande för', breakfast: 'Frukostbuffé',
    downloadNote: 'CSV-filer kan öppnas i Excel och andra kalkylprogram. Priserna anges i euro inklusive moms.',
    dailyNote: 'Dagens CSV gäller endast angivet datum. Den fullständiga listan innehåller namngivna rätter från det senast publicerade dagserbjudandet.',
  },
  fi: {
    title: 'Hinnastot ja hintatiedot', reference: 'Hinta päivänä', current: 'Nykyinen hinta',
    explanation: 'Nykyisen hinnan vieressä näkyy ilmoitetun päivän normaalihinta Kroatian hintojen läpinäkyvyyttä koskevien sääntöjen mukaisesti. Se on vertailutieto, ei alennus, ja näkyy myös hinnan pysyessä samana.',
    full: 'Koko hinnasto · CSV', daily: 'Päivän lounas · CSV', archive: 'Hinnastoarkisto', published: 'Julkaistu',
    sources: 'Viralliset lähteet', guidance: 'Talousministeriön ohjeet',
    tiers: 'Marendassa on kuusi hintatasoa. Kunkin tason kohdalla näkyy tänään valmistamamme ruoka. Ruoat vaihtuvat päivittäin ja niitä on saatavilla päivän erän loppumiseen asti.',
    stale: 'Kysy Bistro Putnikin henkilökunnalta päivän lounasruokia, hintoja ja allergeenitietoja.',
    offerDate: 'Tarjonta päivälle', breakfast: 'Aamiaisbuffet',
    downloadNote: 'CSV-tiedostot avautuvat Excelissä ja muissa taulukkolaskentaohjelmissa. Hinnat ovat euroina ja sisältävät arvonlisäveron.',
    dailyNote: 'Päivän CSV koskee vain ilmoitettua päivää. Koko hinnasto sisältää viimeksi julkaistun päivän ruoat nimineen.',
  },
  no: {
    title: 'Prislister og prisinformasjon', reference: 'Pris den', current: 'Gjeldende pris',
    explanation: 'Ved siden av gjeldende pris viser vi ordinær pris på den oppgitte datoen i tråd med kroatiske regler om prisåpenhet. Den er til sammenligning, ikke en rabatt, og vises også når prisen er uendret.',
    full: 'Full prisliste · CSV', daily: 'Dagens lunsj · CSV', archive: 'Prislistearkiv', published: 'Publisert',
    sources: 'Offisielle kilder', guidance: 'Veiledning fra økonomidepartementet',
    tiers: 'Marenda har seks prisnivåer. Hvert nivå viser retten vi lager i dag. Rettene endres daglig og serveres så lenge dagens porsjoner rekker.',
    stale: 'Spør personalet på Bistro Putnik om dagens lunsjretter, priser og allergener.',
    offerDate: 'Tilbud for', breakfast: 'Frokostbuffé',
    downloadNote: 'CSV-filer kan åpnes i Excel og andre regnearkprogrammer. Prisene er i euro og inkluderer merverdiavgift.',
    dailyNote: 'Dagens CSV gjelder bare den oppgitte datoen. Den fulle listen inkluderer navngitte retter fra det sist publiserte dagstilbudet.',
  },
  pl: {
    title: 'Cenniki i informacje o cenach', reference: 'Cena w dniu', current: 'Aktualna cena',
    explanation: 'Obok aktualnej ceny pokazujemy cenę regularną z podanego dnia zgodnie z chorwackimi zasadami przejrzystości cen. Służy ona porównaniu, nie oznacza rabatu i jest widoczna także wtedy, gdy cena się nie zmieniła.',
    full: 'Pełny cennik · CSV', daily: 'Lunch dnia · CSV', archive: 'Archiwum cenników', published: 'Opublikowano',
    sources: 'Oficjalne źródła', guidance: 'Wyjaśnienia Ministerstwa Gospodarki',
    tiers: 'Marenda ma sześć poziomów cenowych. Przy każdym poziomie pokazujemy danie przygotowywane dzisiaj. Dania zmieniają się codziennie i są dostępne do wyczerpania dziennej porcji.',
    stale: 'Zapytaj nasz personel w Bistro Putnik o dzisiejsze dania lunchowe, ceny i alergeny.',
    offerDate: 'Oferta na', breakfast: 'Bufet śniadaniowy',
    downloadNote: 'Pliki CSV można otworzyć w Excelu i innych arkuszach kalkulacyjnych. Ceny podano w euro z VAT.',
    dailyNote: 'Dzienny CSV dotyczy tylko podanej daty. Pełny cennik zawiera nazwy dań z ostatnio opublikowanej oferty dnia.',
  },
  da: {
    title: 'Prislister og prisinformation', reference: 'Pris den', current: 'Aktuel pris',
    explanation: 'Ved siden af den aktuelle pris viser vi normalprisen på den angivne dato efter kroatiske regler om prisgennemsigtighed. Den er til sammenligning, ikke en rabat, og vises også ved uændret pris.',
    full: 'Fuld prisliste · CSV', daily: 'Dagens frokost · CSV', archive: 'Prislistearkiv', published: 'Offentliggjort',
    sources: 'Officielle kilder', guidance: 'Økonomiministeriets vejledning',
    tiers: 'Marenda har seks prisniveauer. Hvert niveau viser retten, vi tilbereder i dag. Retterne skifter dagligt og serveres, så længe dagens portioner rækker.',
    stale: 'Spørg vores personale på Bistro Putnik om dagens frokostretter, priser og allergener.',
    offerDate: 'Tilbud for', breakfast: 'Morgenmadsbuffet',
    downloadNote: 'CSV-filer kan åbnes i Excel og andre regnearksprogrammer. Priserne er i euro inklusive moms.',
    dailyNote: 'Dagens CSV gælder kun den angivne dato. Den fulde liste indeholder navngivne retter fra det senest offentliggjorte dagstilbud.',
  },
  hu: {
    title: 'Árlisták és árinformációk', reference: 'Ár ezen a napon:', current: 'Jelenlegi ár',
    explanation: 'A jelenlegi ár mellett a feltüntetett napon érvényes normál árat is megjelenítjük a horvát árátláthatósági szabályok szerint. Ez összehasonlításra szolgál, nem kedvezmény, és változatlan ár esetén is látható.',
    full: 'Teljes árlista · CSV', daily: 'Napi ebéd · CSV', archive: 'Árlistaarchívum', published: 'Közzétéve',
    sources: 'Hivatalos források', guidance: 'A Gazdasági Minisztérium tájékoztatója',
    tiers: 'A marenda hat árszintet tartalmaz. Minden szintnél a ma készített étel látható. Az ételek naponta változnak, és a napi mennyiség erejéig kaphatók.',
    stale: 'A mai ebédételekről, árakról és allergénekről érdeklődjön a Bistro Putnik személyzeténél.',
    offerDate: 'Ajánlat dátuma', breakfast: 'Reggeli büfé',
    downloadNote: 'A CSV-fájlok Excelben és más táblázatkezelőkben nyithatók meg. Az árak euróban értendők és tartalmazzák az áfát.',
    dailyNote: 'A napi CSV csak a feltüntetett dátumra érvényes. A teljes lista tartalmazza a legutóbb közzétett napi ajánlat név szerint felsorolt ételeit.',
  },
};

export function getPriceCopy(locale = 'en') { return priceCopy[locale] || priceCopy.en; }
